In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [18]:
df =  pd.read_csv('titanic.csv')
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    object
 4   Name         891 non-null    object
 5   Sex          891 non-null    object
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    object
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    object
 12  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB

In [20]:
df.isna().sum()

Unnamed: 0       0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
df.describe()

,Unnamed: 0,PassengerId,Survived,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,445.000000,446.000000,0.383838,29.699118,0.523008,0.381594,32.204208
std,257.353842,257.353842,0.486592,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000
25%,222.500000,223.500000,0.000000,20.125000,0.000000,0.000000,7.910400
50%,445.000000,446.000000,0.000000,28.000000,0.000000,0.000000,14.454200
75%,667.500000,668.500000,1.000000,38.000000,1.000000,0.000000,31.000000
max,890.000000,891.000000,1.000000,80.000000,8.000000,6.000000,512.329200

In [22]:
# Lowercase all column names in df for uniformity
df.columns = df.columns.str.lower()

features = ["pclass", "sex", "age", "sibsp", "parch", "fare", "embarked"]
target = "survived"

X = df[features]
y = df[target]

print(f"Count distribution of the target column on the whole dataset: \n{y.value_counts()}")

Count distribution of the target column on the whole dataset:
survived
0    549
1    342
Name: count, dtype: int64

#### Train-Test Split

In [23]:
from sklearn.model_selection import train_test_split

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)  # stratify preserve class distribution

print(f"Training set size: {len(X_train)}")
print(f"Testing set size: {len(X_test)}")

Training set size: 712
Testing set size: 179

In [24]:
# Alternative
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)  # stratify preserve class distribution

print(f"Count distribution of the target column on the train_set: \n{y_train.value_counts()}")
print(f"Count distribution of the target column on the test_set: \n{y_test.value_counts()}")

Count distribution of the target column on the train_set:
survived
0    439
1    273
Name: count, dtype: int64
Count distribution of the target column on the test_set:
survived
0    110
1     69
Name: count, dtype: int64

In [25]:
numeric_features = ["age", 'sibsp', 'parch', 'fare']
catergorical_features = ["pclass", "sex", "embarked"]

#### Numeric Pipeline

Steps:
1. Impute missing values using median
2. Apply StandardScaler

Why median?
- Robust to outliers

Why scaling?
KNN uses distance calculations, if features are not scaled , variables like fare could dominate Age

Scaling ensures all numeric features contribute equally

In [ ]:
numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')), # Impute missing values with median
    ('scaler', StandardScaler())  # Standardize features
])